"use client";
import { useState, useEffect } from "react";

export default function Page() {
  // Static Stories (Standard Requirement)
  const [staticStories, setStaticStories] = useState<any[]>([]);
  
  // Dynamic Inputs (1.0 Requirement)
  const [file, setFile] = useState<File | null>(null);
  const [stichpunkte, setStichpunkte] = useState("");
  const [dynamicResult, setDynamicResult] = useState<{text: string, imageUrl: string} | null>(null);
  const [loading, setLoading] = useState(false);

  // Load static JSON on mount
  useEffect(() => {
    fetch("/story-data.json") // Generated by your .mjs script
      .then((res) => res.json())
      .then((data) => setStaticStories(data))
      .catch((e) => console.log("Run the .mjs script first!"));
  }, []);

  const handleGenerate = async () => {
    if (!file || !stichpunkte) return alert("Please upload a file and add text.");
    
    setLoading(true);
    const formData = new FormData();
    formData.append("file", file);
    formData.append("stichpunkte", stichpunkte);

    const res = await fetch("/api/generate-dynamic", {
      method: "POST",
      body: formData,
    });

    const data = await res.json();
    setDynamicResult(data);
    setLoading(false);
  };

  return (
  <div className="min-h-screen bg-gray-50 p-8 font-sans text-gray-900"> {/* <--- FIX: Added text-gray-900 globally */}
    
    <div className="max-w-4xl mx-auto space-y-12">
      
      {/* SECTION 1: Static Stories */}
      <section>
        <h1 className="text-3xl font-bold mb-6 text-black">Die Geschichte </h1> {/* <--- FIX: text-black */}
        <div className="space-y-8">
          {staticStories.map((story) => (
            <div key={story.chapter} className="border p-6 rounded-xl flex flex-col md:flex-row gap-6 bg-white shadow-sm">
              <img src={story.imagePath} className="w-48 h-48 rounded-lg bg-gray-100 object-cover shadow-sm" />
              <div className="flex-1">
                <h2 className="text-xl font-bold text-gray-800">Kapitel {story.chapter}</h2>
                {/* FIX: Explicitly set text color for the poem */}
                <p className="whitespace-pre-line my-4 text-gray-700 leading-relaxed text-lg">
                  {story.text}
                </p>
                <audio controls src={story.audioPath} className="w-full mt-2" />
              </div>
            </div>
          ))}
        </div>
      </section>

      <hr className="border-t-2 border-gray-200" />

      {/* SECTION 2: 1.0 Feature (Dynamic) */}
      <section className="bg-blue-50 p-8 rounded-xl border border-blue-200 shadow-sm">
        <h1 className="text-2xl font-bold mb-6 text-blue-900">1.0 Feature: Eigene Geschichte Generieren</h1>
        
        <div className="grid gap-6 mb-6">
          
          {/* File Input */}
          <div>
            <label className="block text-sm font-bold text-gray-700 mb-2">1. Vorlage (Monster Bild)</label>
            <input 
              type="file" 
              onChange={(e) => setFile(e.target.files?.[0] || null)}
              // FIX: Added text-gray-900 so filename is visible
              className="block w-full text-sm text-gray-900
                file:mr-4 file:py-2.5 file:px-4
                file:rounded-full file:border-0
                file:text-sm file:font-semibold
                file:bg-blue-600 file:text-white
                hover:file:bg-blue-700
                cursor-pointer bg-white rounded-lg border border-gray-300"
            />
          </div>
          
          {/* Text Area */}
          <div>
            <label className="block text-sm font-bold text-gray-700 mb-2">2. Stichpunkte für neue Szene</label>
            <textarea 
              rows={3}
              value={stichpunkte}
              onChange={(e) => setStichpunkte(e.target.value)}
              placeholder="z.B. Das Monster isst ein Eis am Strand..."
              // FIX: Added text-gray-900, bg-white, and distinct border
              className="w-full p-3 border border-gray-300 rounded-lg text-gray-900 bg-white placeholder-gray-500 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
            />
          </div>

          <button 
            onClick={handleGenerate} 
            disabled={loading}
            className="bg-green-600 text-white py-3 px-6 rounded-lg font-bold hover:bg-green-700 disabled:opacity-50 transition-colors shadow-sm"
          >
            {loading ? "Generiere..." : "Generate New Story"}
          </button>
        </div>

        {/* Dynamic Result Display */}
        {dynamicResult && (
          <div className="mt-8 p-6 bg-white rounded-xl shadow border border-green-100 animate-in fade-in slide-in-from-bottom-4 duration-500">
             <h3 className="font-bold text-green-700 mb-4 text-lg">
               Generiertes Ergebnis (auf Vercel Blob gespeichert):
             </h3>
             <div className="flex flex-col md:flex-row gap-6">
                <img src={dynamicResult.imageUrl} className="w-64 h-64 rounded-lg object-cover shadow bg-gray-50" />
                
                {/* FIX: Ensure generated text is dark */}
                <div className="flex-1">
                   <p className="whitespace-pre-line text-gray-800 text-lg leading-relaxed">
                     {dynamicResult.text}
                   </p>
                </div>
             </div>
          </div>
        )}
      </section>
    </div>
  </div>
);}